services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resm_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
      - node_modules_data:/var/www/html/node_modules
    ports:
      - "8000:80"
      - "5173:5173"  # Vite dev server
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE:-resm_db}
      - DB_USERNAME=${DB_USERNAME:-resm_user}
      - DB_PASSWORD=${DB_PASSWORD:-resm_password}
    depends_on:
      - db
    networks:
      - resm_network

  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: resm_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-resm_db}
      POSTGRES_USER: ${DB_USERNAME:-resm_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-resm_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - resm_network

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: resm_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json:ro
    depends_on:
      - db
    networks:
      - resm_network

networks:
  resm_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  vendor_data:
    driver: local
  node_modules_data:
    driver: local
